[project]
authors = ["Andrew Lin <andrew.lin@ieee.org>"]
channels = ["conda-forge"]
name = "paperbot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
paperbot = "python paper_bot.py"
test = "PYTHONPATH=. pytest test"

[dependencies]
python = ">=3.13.2,<3.14"
requests = ">=2.32.3,<3"
atproto = ">=0.0.58,<0.0.59"
pytest = ">=8.3.4,<9"
